language: python

before_script:
- pip install tox

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install -e .
# # command to run tests
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.5
      env: TOXENV=pylint
    - python: 3.5
      env: TOXENV=flake8
    - env: TOXENV=coverage
  fast_finish: true
  allow_failures:
    - python: 3.5
      env: TOXENV=pylint
    - python: 3.5
      env: TOXENV=flake8
